version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: patronus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis
    restart: always
    command: redis-server --appendOnly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_vol:/var/lib/redis/data
  springapp:
    container_name: patronus_app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/patronus
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
      DB_HOST: db
    depends_on:
      - db
      - redis
    command:
      - start
      - --auto-build
volumes:
  postgres_data:
  redis_vol: